# Generated by Django 4.1.2 on 2022-11-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_add_student_student_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='videos/%y/%m/%d')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.subject')),
            ],
        ),
    ]
