# Generated by Django 4.1.2 on 2022-12-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lesson_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='videos/%y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='lesson',
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.subjecte'),
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
