# Generated by Django 4.1.2 on 2022-12-06 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecte',
            name='name',
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='videos/%y/%m/%d')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.subjecte')),
            ],
        ),
    ]
