# Generated by Django 4.1.2 on 2022-12-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_subjecte_name_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='name_lesson',
        ),
        migrations.RenameField(
            model_name='subjecte',
            old_name='name_lesson',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subjecte',
            name='description_lesson',
        ),
        migrations.RemoveField(
            model_name='subjecte',
            name='video',
        ),
    ]
